In [3]:
import pandas as pd

### 메시지 전처리

In [4]:
msg = pd.read_csv('./raw/CUSTOMER_MSG.csv')
print(msg.shape)
msg.head(2)

(4281570, 14)

,STND_YMD,INCS_NO,MSG_SEND_CHN_CD,MSG_SEND_CHN_NM,MSG_SEND_OFR_CHN_CD,MSG_SEND_OFR_CHN_NM,JOUR_ID,JOUR_NM,CAMP_TGT_CHN_CD,CAMP_TGT_CHN_NM,CAMP_TGT_BRND_CD,CAMP_TGT_BRND_NM,MSG_SEND_CNT,ETL_PROC_DTTM
0,2024-10-28,f3f306c20e5caa497df4bbbd4732161eb63f65b92544b3...,FT,카카오 친구톡,IN,이니스프리,5EEB341B-52BF-4707-8B40-C6E811D725B5,IN24102704S_IF_2410_5주차_LEE4554,"[\n ""036""\n]","[\n ""이니스프리 쇼핑몰""\n]","[\n ""11177""\n]","[\n ""이니스프리""\n]",1,2025-01-20 04:46:47.591
1,2024-09-08,906522474e459ca44336c858e76b7f6cc4a8b76abba594...,FT,카카오 친구톡,IN,이니스프리,1AFE739B-45FD-44AB-8206-0D4A29641558,IN24090411S_IF_2409_레티놀패드_크림,"[\n ""036""\n]","[\n ""이니스프리 쇼핑몰""\n]","[\n ""11177""\n]","[\n ""이니스프리""\n]",1,2025-01-20 04:46:47.591

In [7]:
msg.iloc[0]['JOUR_NM'].split('_')[0]

'IN24102704S'

In [9]:
def jour(text):
    return text.split('_')[0]

msg['JOUR'] = msg['JOUR_NM'].apply(jour)
msg.head(2)

,STND_YMD,INCS_NO,MSG_SEND_CHN_CD,MSG_SEND_CHN_NM,MSG_SEND_OFR_CHN_CD,MSG_SEND_OFR_CHN_NM,JOUR_ID,JOUR_NM,CAMP_TGT_CHN_CD,CAMP_TGT_CHN_NM,CAMP_TGT_BRND_CD,CAMP_TGT_BRND_NM,MSG_SEND_CNT,ETL_PROC_DTTM,JOUR
0,2024-10-28,f3f306c20e5caa497df4bbbd4732161eb63f65b92544b3...,FT,카카오 친구톡,IN,이니스프리,5EEB341B-52BF-4707-8B40-C6E811D725B5,IN24102704S_IF_2410_5주차_LEE4554,"[\n ""036""\n]","[\n ""이니스프리 쇼핑몰""\n]","[\n ""11177""\n]","[\n ""이니스프리""\n]",1,2025-01-20 04:46:47.591,IN24102704S
1,2024-09-08,906522474e459ca44336c858e76b7f6cc4a8b76abba594...,FT,카카오 친구톡,IN,이니스프리,1AFE739B-45FD-44AB-8206-0D4A29641558,IN24090411S_IF_2409_레티놀패드_크림,"[\n ""036""\n]","[\n ""이니스프리 쇼핑몰""\n]","[\n ""11177""\n]","[\n ""이니스프리""\n]",1,2025-01-20 04:46:47.591,IN24090411S

In [10]:
msg_dtl = pd.read_csv('./raw/11월_친구톡utm.csv')
msg_dtl['발송시간'] = pd.to_datetime(msg_dtl['발송시간'])
msg_dtl.head(2)

C:\Users\amore\AppData\Local\Temp\ipykernel_12896\249323394.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  msg_dtl['발송시간'] = pd.to_datetime(msg_dtl['발송시간'])

,저니,저니명,버전,발송타입,발송시간,본문,버튼
0,IN24112601S,IN24112601S_이니_광고정보수집안내_241126수기,1,알림톡,2024-11-27 17:06:00,"[안내] 이니스프리\n광고성정보 수신동의 여부 안내\n\n고객님, 이니스프리를 이용...","{""button"":[{""name"":""채널 추가"", ""type"":""AC""}]}"
1,IN24111901S,IN24111901S_이니스프리_가입즉시 알림톡_테스트,7,알림톡,2024-11-22 10:03:00,"[안내] 이니스프리 개인정보 이용내역 안내\n\n최소정님, 이니스프리를 이용해주셔서...","{""button"":[{""name"":""개인정보 이용내역 상세보기"", ""type"":""W..."

In [14]:
msg_merge = pd.merge(msg, msg_dtl, left_on='JOUR', right_on='저니', how='left')
msg_merge['본문'] = msg_merge['본문'].astype(str)
msg_merge = msg_merge[~msg_merge['본문'].str.contains('\[안내\]')]
print(msg_merge.shape)
msg_merge.head(2)

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:3: SyntaxWarning: invalid escape sequence '\['
C:\Users\amore\AppData\Local\Temp\ipykernel_12896\232638684.py:3: SyntaxWarning: invalid escape sequence '\['
  msg_merge = msg_merge[~msg_merge['본문'].str.contains('\[안내\]')]

(4931532, 22)

,STND_YMD,INCS_NO,MSG_SEND_CHN_CD,MSG_SEND_CHN_NM,MSG_SEND_OFR_CHN_CD,MSG_SEND_OFR_CHN_NM,JOUR_ID,JOUR_NM,CAMP_TGT_CHN_CD,CAMP_TGT_CHN_NM,...,MSG_SEND_CNT,ETL_PROC_DTTM,JOUR,저니,저니명,버전,발송타입,발송시간,본문,버튼
0,2024-10-28,f3f306c20e5caa497df4bbbd4732161eb63f65b92544b3...,FT,카카오 친구톡,IN,이니스프리,5EEB341B-52BF-4707-8B40-C6E811D725B5,IN24102704S_IF_2410_5주차_LEE4554,"[\n ""036""\n]","[\n ""이니스프리 쇼핑몰""\n]",...,1,2025-01-20 04:46:47.591,IN24102704S,IN24102704S,IN24102704S_IF_2410_5주차_LEE4554,2,친구톡,2024-10-28 11:00:00,"이니스프리 | Lee 토트백 소진 임박 (우와)\n\n· 25,000원 구매 시, ...","{""button"":[{""name"":""구경 가기▶"", ""type"":""AL"", ""sch..."
1,2024-09-08,906522474e459ca44336c858e76b7f6cc4a8b76abba594...,FT,카카오 친구톡,IN,이니스프리,1AFE739B-45FD-44AB-8206-0D4A29641558,IN24090411S_IF_2409_레티놀패드_크림,"[\n ""036""\n]","[\n ""이니스프리 쇼핑몰""\n]",...,1,2025-01-20 04:46:47.591,IN24090411S,IN24090411S,IN24090411S_IF_2409_레티놀패드_크림,2,친구톡,2024-09-08 11:00:00,[33% 할인] 레티놀 러버(하트) 희소식!\n지금 사면 패드 2개가 3만원 초반대...,"{""button"":[{""name"":""구경 가기▶"", ""type"":""AL"", ""sch..."

In [15]:
msg_merge[msg_merge['저니'].notna()].to_csv('./data/MSG.csv')

In [16]:
cust_list = list(set(msg_merge['INCS_NO']))
cust_df = pd.DataFrame(cust_list, columns=['INCS_NO'])
print(cust_df.shape)
cust_df.head(2)

(547404, 1)

                                             INCS_NO
0  2ccee623f083233f9082eca9345144c14c692c65a66f8e...
1  b9958df4df9af4e43c040650881be2365e5346c29e07e9...

In [1]:
# log 1,2,3 모두 처리
i = 2
input_path = f'./raw/LOG{i}.csv'
output_path = f'./data/LOG{i}.csv'

log = pd.read_csv(input_path)
print(log.shape)

log_sampl = pd.merge(log, cust_df, on='INCS_NO', how='inner')
print(log_sampl.shape)

log_sampl.to_csv(output_path)

NameError: name 'pd' is not defined